export const colleges = [
  {
    id: "0",
    value: "humanities",
    college: "인문대학",
    departments: [
      "국어국문학과",
      "영어영문학과",
      "불어불문학과",
      "독어독문학과",
      "중어중문학과",
      "고고인류학과",
      "일어일문학과",
      "노어노문학과",
      "한문학과",
      "사학과",
      "철학과",
    ],
  },
  {
    id: "1",
    value: "social_science",
    college: "사회과학대학",
    departments: [
      "정치외교학과",
      "사회학과",
      "지리학과",
      "문헌정보학과",
      "심리학과",
      "사회복지학부",
      "미디어커뮤니케이션학과",
      "행정학과",
    ],
  },
  {
    id: "2",
    value: "natural_science",
    college: "자연과학대학",
    departments: [
      "수학과",
      "물리학과",
      "화학과",
      "생명과학부",
      "지구과학과",
      "통계학과",
      "지리학과",
    ],
  },
  {
    id: "3",
    value: "economy_and_commerce",
    college: "경상대학",
    departments: ["경영학과", "경제학과"],
  },
  {
    id: "4",
    value: "engineering",
    college: "공과대학",
    departments: [
      "기계공학과",
      "화학공학과",
      "재료공학과",
      "건축학과",
      "산업공학과",
      "신소재공학과",
      "에너지공학과",
      "섬유시스템공학과",
      "고분자공학과",
      "환경공학과",
      "항공우주공학과",
    ],
  },
  {
    id: "5",
    value: "it",
    college: "IT대학",
    departments: ["컴퓨터공학과", "전기공학과", "전자공학과"],
  },
  {
    id: "6",
    value: "agriculture_and_life_science",
    college: "농업생명과학대학",
    departments: [
      "식품학과",
      "산림과학과",
      "식물생산과학과",
      "바이오소재학과",
      "응용생명과학과",
    ],
  },
  {
    id: "7",
    value: "art",
    college: "예술대학",
    departments: [
      "음악학과",
      "국악학과",
      "미술학과",
      "디자인학과",
      "영상학과",
      "연기예술학과",
      "의상학과",
    ],
  },
  {
    id: "8",
    value: "education",
    college: "사범대학",
    departments: [
      "교육학과",
      "국어교육과",
      "영어교육과",
      "독어교육전공",
      "불어교육전공",
      "역사교육과",
      "일반사회교육과",
      "윤리교육과",
      "화학교육과",
      "지구과학교육과",
      "체육교육과",
      "지리교육과",
      "물리교육과",
      "수학교육과",
      "생물교육과",
      "가정교육과",
    ],
  },
  {
    id: "9",
    value: "medical",
    college: "의과대학",
    departments: ["의예과", "의학과"],
  },
  {
    id: "10",
    value: "dental",
    college: "치과대학",
    departments: ["치의학과", "치의예과"],
  },
  {
    id: "11",
    value: "veterinary",
    college: "수의과대학",
    departments: ["수의학과", "수의예과"],
  },
  {
    id: "13",
    value: "nursing",
    college: "간호대학",
    departments: ["간호학과"],
  },
  {
    id: "14",
    value: "medicine",
    college: "약학대학",
    departments: ["약학과"],
  },
  {
    id: "15",
    value: "ecology_and_environment",
    college: "생태환경대학",
    departments: [
      "생태환경시스템학과",
      "레저스포츠학과",
      "축산학과",
      "축산생명과학과",
      "곤충생명과학과",
      "말-특수동물학과",
      "관광학과",
    ],
  },
];
